Repository crypto-sentiment/crypto_sentiment_demo_app, pull requests merged in 2022-06, with the labels that each got.

#3 label studio
  .env.example
  README.md
  conf/config.yaml
  crypto_sentiment_demo_app/label_studio/Dockerfile
  crypto_sentiment_demo_app/label_studio/__init__.py
  crypto_sentiment_demo_app/label_studio/data.py
  crypto_sentiment_demo_app/label_studio/label_studio.py
  crypto_sentiment_demo_app/label_studio/main.py
  crypto_sentiment_demo_app/label_studio/modify_tasks.sh
  crypto_sentiment_demo_app/label_studio/requirements.txt
  crypto_sentiment_demo_app/label_studio/sampler.py
  crypto_sentiment_demo_app/model_scorer/model_scorer.py
  crypto_sentiment_demo_app/utils.py
  db_setup/docker_postgres_init.sql
  docker-compose.yml
Labels: enhancement

#11 RSS feed crawler with filtering
  .flake8
  README.md
  conf/config.yaml
  conf/logger/base.yaml
  config.yml
  crypto_sentiment_demo_app/crawler/Dockerfile
  crypto_sentiment_demo_app/crawler/crawler.py
  crypto_sentiment_demo_app/crawler/processor.py
  crypto_sentiment_demo_app/crawler/requirements.txt
  crypto_sentiment_demo_app/data_provider/api.py
  crypto_sentiment_demo_app/data_provider/db_connector.py
  crypto_sentiment_demo_app/data_provider/requirements.txt
  crypto_sentiment_demo_app/data_provider/schemas.py
  crypto_sentiment_demo_app/frontend/requirements.txt
  crypto_sentiment_demo_app/model_inference_api/requirements.txt
  crypto_sentiment_demo_app/model_scorer/model_scorer.py
  crypto_sentiment_demo_app/model_scorer/requirements.txt
  crypto_sentiment_demo_app/models/inference/base.py
  crypto_sentiment_demo_app/models/train/base.py
  crypto_sentiment_demo_app/models/train/tf_idf.py
  crypto_sentiment_demo_app/train/requirements-cpu.txt
  crypto_sentiment_demo_app/utils.py
  data/crypto_rss_feeds.txt
  data/crypto_rss_feeds_toy.txt
  docker-compose.yml
Labels: enhancement

#14 Scheduler for crawler and model scorer
  README.md
  crypto_sentiment_demo_app/crawler/crawler.py
  crypto_sentiment_demo_app/label_studio/requirements.txt
  crypto_sentiment_demo_app/model_scorer/model_scorer.py
  docker-compose.yml
Labels: enhancement

#17 fix/write filtered news to DB instead of unfiltered
  crypto_sentiment_demo_app/crawler/crawler.py
  crypto_sentiment_demo_app/model_scorer/model_scorer.py
Labels: minor_fix

#7 frontend react module
  .gitignore
  .pre-commit-config.yaml
  README.md
  crypto_sentiment_demo_app/frontend/Dockerfile
  crypto_sentiment_demo_app/frontend/README.md
  crypto_sentiment_demo_app/frontend/__init__.py
  crypto_sentiment_demo_app/frontend/package-lock.json
  crypto_sentiment_demo_app/frontend/package.json
  crypto_sentiment_demo_app/frontend/public/favicon.ico
  crypto_sentiment_demo_app/frontend/public/img/git.svg
  crypto_sentiment_demo_app/frontend/public/img/github_white.svg
  crypto_sentiment_demo_app/frontend/public/img/logo.png
  crypto_sentiment_demo_app/frontend/public/img/man/arrow.svg
  crypto_sentiment_demo_app/frontend/public/img/man/back.svg
  crypto_sentiment_demo_app/frontend/public/img/man/leftside.svg
  crypto_sentiment_demo_app/frontend/public/img/man/middleside.svg
  crypto_sentiment_demo_app/frontend/public/img/man/rightside.svg
  crypto_sentiment_demo_app/frontend/public/index.html
  crypto_sentiment_demo_app/frontend/public/manifest.json
  crypto_sentiment_demo_app/frontend/public/robots.txt
  crypto_sentiment_demo_app/frontend/src/App.js
  crypto_sentiment_demo_app/frontend/src/components/Chart/index.js
  crypto_sentiment_demo_app/frontend/src/components/HistoricalValues/HistoricalValues.module.scss
  crypto_sentiment_demo_app/frontend/src/components/HistoricalValues/IndexLine.js
  crypto_sentiment_demo_app/frontend/src/components/HistoricalValues/index.js
  crypto_sentiment_demo_app/frontend/src/components/Manometer/Manometer.module.scss
  crypto_sentiment_demo_app/frontend/src/components/Manometer/index.js
  crypto_sentiment_demo_app/frontend/src/components/News/News.module.scss
  crypto_sentiment_demo_app/frontend/src/components/News/NewsLine.js
  crypto_sentiment_demo_app/frontend/src/components/News/index.js
  crypto_sentiment_demo_app/frontend/src/index.js
  crypto_sentiment_demo_app/frontend/src/index.scss
  crypto_sentiment_demo_app/frontend/streamlit_app.py
  docker-compose.yml
  static/img/react_front_app1.png
  static/img/react_front_app2.png
Labels: enhancement

#20 add a script to write from CSV to Postgres
  .gitignore
  README.md
  crypto_sentiment_demo_app/database/docker_pgadmin_servers.json
  crypto_sentiment_demo_app/database/docker_postgres_init.sql
  crypto_sentiment_demo_app/database/write_df_to_db.py
  crypto_sentiment_demo_app/database/write_df_to_db.sh
  docker-compose.yml
Labels: enhancement

#22 ofelia scheduler for Label Studio imports/exports
  .env.example
  README.md
  crypto_sentiment_demo_app/crawler/crawler.py
  crypto_sentiment_demo_app/crawler/processor.py
  crypto_sentiment_demo_app/label_studio/label_studio.py
  crypto_sentiment_demo_app/label_studio/main.py
  crypto_sentiment_demo_app/label_studio/modify_tasks.sh
  docker-compose.yml
Labels: enhancement

#21 add self-hosted github runner
  .github/workflows/lint_tests.yml
  .github/workflows/publish_docker_images.yml
  README.md
  crypto_sentiment_demo_app/model_inference_api/requirements.txt
  crypto_sentiment_demo_app/model_scorer/requirements.txt
  docker-compose.test.yml
  run_tests.sh
  tests/model_inference_api/test_dummy.py
  tests/model_scorer/test_dummy.py
Labels: enhancement

#30 redirect pycache files into tmp
  crypto_sentiment_demo_app/crawler/Dockerfile
  crypto_sentiment_demo_app/data_provider/Dockerfile
  crypto_sentiment_demo_app/label_studio/Dockerfile
  crypto_sentiment_demo_app/model_inference_api/Dockerfile
  crypto_sentiment_demo_app/model_scorer/Dockerfile
  crypto_sentiment_demo_app/train/Dockerfile-cpu
  crypto_sentiment_demo_app/train/Dockerfile-gpu
Labels: minor_fix

#28 Fix issue with Mac .env variables
  README.md
  crypto_sentiment_demo_app/label_studio/modify_tasks.sh
Labels: minor_fix

#32 fix/front fetch
  .env.example
  crypto_sentiment_demo_app/data_provider/api.py
  crypto_sentiment_demo_app/frontend/Dockerfile
  crypto_sentiment_demo_app/frontend/package-lock.json
  crypto_sentiment_demo_app/frontend/package.json
  crypto_sentiment_demo_app/frontend/src/App.js
  crypto_sentiment_demo_app/frontend/src/components/Chart/index.js
  crypto_sentiment_demo_app/frontend/src/components/News/index.js
  docker-compose.yml
Labels: bug

#27 Feature/mlflow
  .env.example
  .gitignore
  README.md
  conf/model/bert.yaml
  conf/model/tf_idf.yaml
  conf/nginx.conf
  crypto_sentiment_demo_app/mlflow_server/Dockerfile
  crypto_sentiment_demo_app/mlflow_server/create_bucket.py
  crypto_sentiment_demo_app/mlflow_server/requirements.txt
  crypto_sentiment_demo_app/mlflow_server/start.sh
  crypto_sentiment_demo_app/model_inference_api/requirements.txt
  crypto_sentiment_demo_app/models/inference/base.py
  crypto_sentiment_demo_app/models/inference/bert.py
  crypto_sentiment_demo_app/models/inference/tf_idf.py
  crypto_sentiment_demo_app/models/train/base.py
  crypto_sentiment_demo_app/models/train/bert/model.py
  crypto_sentiment_demo_app/models/train/tf_idf.py
  crypto_sentiment_demo_app/train/requirements-cpu.txt
  crypto_sentiment_demo_app/train/requirements-gpu.txt
  crypto_sentiment_demo_app/train/train.py
  docker-compose.yml
Labels: enhancement

#36 remove uvicorn reload; deploy bert instead of tf-idf&logreg
  conf/config.yaml
  docker-compose.yml
Labels: enhancement

#39 Feature/add license
  LICENSE.md
Labels: documentation
